echo === INSTALL COMMON EXTENSIONS ===
code `
--install-extension shakram02.bash-beautify `
--install-extension coenraads.bracket-pair-colorizer `
--install-extension ms-azuretools.vscode-docker `
--install-extension grapecity.gc-excelviewer `
--install-extension eamodio.gitlens `
--install-extension ms-ceintl.vscode-language-pack-ja `
--install-extension orta.vscode-jest `
--install-extension shd101wyy.markdown-preview-enhanced `
--install-extension davidanson.vscode-markdownlint `
--install-extension ibm.output-colorizer `
--install-extension jebbs.plantuml `
--install-extension chrmarti.regex `
--install-extension shuworks.vscode-table-formatter `
--install-extension shardulm94.trailing-spaces `
--install-extension vscodevim.vim `
--install-extension ms-vscode-remote.remote-containers `
--install-extension ms-vscode-remote.remote-ssh `
--install-extension ms-vscode-remote.remote-ssh-edit `
--install-extension ms-vscode-remote.remote-ssh-explorer `
--install-extension ms-vscode-remote.remote-wsl `
--install-extension ms-vscode-remote.vscode-remote-extensionpack
